// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBH3doruVT7GnQXFztJobUlA83JTm3Q9FU',
    appId: '1:749841411870:web:c23650dd7400a19b3e230f',
    messagingSenderId: '749841411870',
    projectId: 'sport-app-61830',
    authDomain: 'sport-app-61830.firebaseapp.com',
    databaseURL: 'https://sport-app-61830-default-rtdb.firebaseio.com',
    storageBucket: 'sport-app-61830.firebasestorage.app',
    measurementId: 'G-JR0607DGE7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv2VXJ1-aUzgErUbBg9QHgKKovbjWNYz4',
    appId: '1:749841411870:android:c3fd13c7ad9f8d6d3e230f',
    messagingSenderId: '749841411870',
    projectId: 'sport-app-61830',
    databaseURL: 'https://sport-app-61830-default-rtdb.firebaseio.com',
    storageBucket: 'sport-app-61830.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYX07IhuFvpYzgatPkO99QxKRZtTOVHmE',
    appId: '1:749841411870:ios:d06810361d60b54d3e230f',
    messagingSenderId: '749841411870',
    projectId: 'sport-app-61830',
    databaseURL: 'https://sport-app-61830-default-rtdb.firebaseio.com',
    storageBucket: 'sport-app-61830.firebasestorage.app',
    iosBundleId: 'com.example.mobilsportt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBH3doruVT7GnQXFztJobUlA83JTm3Q9FU',
    appId: '1:749841411870:web:4250160f218f97e13e230f',
    messagingSenderId: '749841411870',
    projectId: 'sport-app-61830',
    authDomain: 'sport-app-61830.firebaseapp.com',
    databaseURL: 'https://sport-app-61830-default-rtdb.firebaseio.com',
    storageBucket: 'sport-app-61830.firebasestorage.app',
    measurementId: 'G-KGY8G0YN59',
  );
}
